name: Lint

on:
  pull_request:

jobs:
  lint-main-agent:
    name: Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "backend/uv.lock"
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run lint checks
        run: uv run ruff check .

      - name: Run mypy
        run: uv run mypy src/

  lint-receptionist-agent:
    name: Lint frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
